global:
  scrape_interval: 15s # How frequently to scrape targets
  query_log_file: /prometheus/query.log

scrape_configs:
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['node-app:3000']