name: Deploy and Test Application

on:
  push:
    branches:
      - main

jobs:
  deploy_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Append logs to file
        run: |
          echo "=== Additional Logs ===" >> applogs.txt
          echo "Timestamp: $(date)" >> applogs.txt
          echo "Build completed successfully." >> applogs.txt

      - name: Install dependencies
        run: npm install > applogs.txt 2>&1

      - name: Build application
        run:  npx tsc -b > applogs.txt 2>&1
    
      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: applogs
          path: applogs.txt

